FROM node:latest as BUILDER

WORKDIR /src
COPY ./frontend .
RUN npm install
RUN npm run build

FROM node:latest
RUN npm install http-server -g
WORKDIR /app
COPY --from=builder /src/dist/frontend ./frontend

EXPOSE 8081
CMD ["http-server", "-p", "8081", "/app/frontend"]
